### ISSUE TITLE
ModuleNotFoundError: No module named 'cassandra'

### ISSUE THREAD

**Issue by d-ganchar** [mikicaivosevic/flask-cassandra-sessions#1]
Hello.
Thanks for your package.

Your package requires **cassandra-driver**.  I propose to add dependency to **setup.py**.

```
setup(
     install_requires=['cassandra-driver'],
     ...
```

Otherwise, we get the following error(and we need to install dependency manually):

```
  from cassandra_flask_sessions import CassandraSessionInterface
  File "../cassandra_flask_sessions/__init__.py", line 6, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
```

What do you think?

**Comment by mikicaivosevic** [comment]
👍 
Can you create a pull request ?

**Comment by d-ganchar** [comment]
@mikicaivosevic no problem. thanks
