### ISSUE TITLE
add user and password into CassandraSessionInterface

### ISSUE THREAD

**Issue by d-ganchar** [mikicaivosevic/flask-cassandra-sessions#3]
At the moment the are no possibility to set `username` and `password`. Because `CassandraSessionInterface` initializes `Cluster` without `auth_provider` argument. I propose to add `username` and `password` into `CassandraSessionInterface.__init__()`. Example:

```
class CassandraSessionInterface(SessionInterface):

    def __init__(self, keyspace, cluster=None, port=9042, username=None, password=None):
            if username and password:
                   auth_provider = PlainTextAuthProvider(username, password))
            else:
                  auth_provider = None
            cluster = Cluster(cluster, port=port, auth_provider=auth_provider)
            # ....
```

What do you think?

**Comment by mikicaivosevic** [comment]
I agree with you proposal 👍 Please create  pull request

**Comment by d-ganchar** [comment]
@mikicaivosevic ok. thanks
